#!/bin/sh
#
# Starts Fenrir
#

# Allow a few customizations from a config file

setMAC() {
	serial=$(awk -F" *: *" '/Serial/{print $2}' /proc/cpuinfo)
	mac=$(echo $serial | md5sum | sed 's/^\(..\)\(..\)\(..\)\(..\)\(..\)\(..\).*$/\1:\2:\3:\4:\5:\6/')
	mac=$(echo $mac | awk '{print "02:" substr($0,4,14)}')
	ip link set dev eth0 address $mac
}

checkDHCP() {
	NETFILE=/storage/networkInterfaces
	if [ ! -f ${NETFILE} ]; then
		echo "auto eth0 lo" > ${NETFILE}
		echo "iface lo inet loopback" >> ${NETFILE}
		echo "allow-hotplug eth0" >> ${NETFILE}
		echo "iface eth0 inet dhcp" >> ${NETFILE}
	fi
}

start() {
	printf "Preparing Network "
	setMAC
	checkDHCP
	echo "OK"
}
stop() {
	printf "Stopping Network prepare "
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
