#!/bin/sh

IFS=','
TABLES="settings,ipconnectionmap,vpnprofiles,profilepassword"
PID=0

isdifferent() {
    if [ $# -lt 2 ]; then
        return 0
    fi
    db1=$1
    db2=$2
    set -- ${TABLES}
    for table in "$@"; do
        diff=$(sqlite3 "${db1}" "attach \"${db2}\" as db2;SELECT * FROM ${table} EXCEPT SELECT * from db2.${table};" 2>&1)
        [ -n "$diff" ] && return 0
        diff=$(sqlite3 "${db2}" "attach \"${db1}\" as db2;SELECT * FROM ${table} EXCEPT SELECT * from db2.${table};" 2>&1 )
        [ -n "$diff" ] && return 0
    done
    return 1
}

monitor() {
    DBPATH1=/storage/fenrir.sqlite
    DBPATH2=/var/cache/fenrir/fenrir.sqlite
    [ -e ${DBPATH1} ] || touch ${DBPATH1}
    [ -e ${DBPATH2} ] || touch ${DBPATH2}
    local END="0"
    trap "END=1; exit 0" SIGTERM
    while [ "${END}" = "0" ]; do
        inotifywait -q -e modify ${DBPATH2} >/dev/null
        if isdifferent ${DBPATH1} ${DBPATH2}; then
            cp -f ${DBPATH2} ${DBPATH1}.tmp
	    mv ${DBPATH1}.tmp ${DBPATH1}
	    mount -o remount,sync /storage
        fi
    done
}

start() {
        printf "Starting Fenrir Database Monitor: "
        monitor &
        PID=$!
        echo "OK"
}
stop() {
        printf "Stopping Fenrir Database Monitor: "
        kill ${PID}
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
